import Nav from "@/components/Nav";
import "./globals.css";
import TransitionProvider from "@/providers/TransitionProvider";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TransitionProvider>
        <Nav/>
        {children}
        </TransitionProvider>
      </body>
    </html>
  );
}
